# https://travis-ci.org/HearthSim/django-intenumfield
sudo: false
language: python

python:
  - 3.6

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36
  - TOXENV=flake8

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_failure: always
    on_success: change
