# https://travis-ci.org/HearthSim/django-intenumfield
sudo: false
language: python

python: "3.6"

env:
  - TOXENV=py36-django20
  - TOXENV=py36-djangomaster
  - TOXENV=flake8

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox
