# https://travis-ci.org/HearthSim/django-intenumfield
language: python

python: "3.6"

env:
  - TOXENV=py36-django20
  - TOXENV=py36-django22
  - TOXENV=py36-django32
  - TOXENV=flake8

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install tox

script:
  - tox

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      install:
        - pip install --upgrade pip setuptools wheel

      script: echo Releasing $TRAVIS_TAG

      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        distributions: "sdist bdist_wheel"
        on:
          tags: true
